spring.application.name=bff-agendador

usuario.url=localhost:8080/usuario
agendador-tarefas.url=localhost:8081/tarefas
notificacao.url=localhost:8082/email

cron.horario=0/30 0/1 * * * ?

usuario.email=admim@admim.com
usuario.senha=1234

Server.port=8083
